### ISSUE TITLE
how to run this project?

### ISSUE THREAD

**Issue by Zeb-D** [xphh/happor#2]
hi , first download this project ,after run ServerMain.class  main  function;
but has Exceptioned:

`java.io.FileNotFoundException: C:\Users\Administrator\Desktop\ht.jar (系统找不到指定的路径。)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:103)
	at cn.lechange.happor.utils.PackageUtil.getClassNameByJar(PackageUtil.java:108)
	at cn.lechange.happor.utils.PackageUtil.getClassNameByJars(PackageUtil.java:166)
	at cn.lechange.happor.utils.PackageUtil.getClassName(PackageUtil.java:61)
	at cn.lechange.happor.utils.PackageUtil.getClassName(PackageUtil.java:38)
	at cn.lechange.happor.container.JarImporter.load(JarImporter.java:48)
	at cn.lechange.happor.container.JarContainerServer.load(JarContainerServer.java:109)
	at cn.lechange.happor.container.JarContainerServer$1.run(JarContainerServer.java:155)
	at java.util.TimerThread.mainLoop(Timer.java:555)`

can you help me to run this project ,thanks !
and  "conf/containerServer.xml" this file not in this project ...
and  fix this project some problem by the way !

**Comment by xphh** [comment]
很久没维护啦，工作和生活都很忙，可能没时间看。这个看起来像是环境的问题，你自己再调试调试。

不过你为什么不用springboot呢？现在springboot已经很成熟啦，完全覆盖我写的这个框架。建议你用springboot。


在 2018年05月26日 11:46, ZouYd 写道:
